api: 2

core: 8.x

projects:
  drupal: 8.0.x
  key_value: 1.x
  multiversion:
    type: module
    download:
      type: git
      branch: refactor-ContentEntityStorageTrait-2
      url: "https://github.com/dickolsson/drupal-multiversion.git"
  replication:
    type: module
    download:
      type: git
      branch: bulk-docs
      url: "https://github.com/relaxedws/drupal-replication.git"
